name: SSRefund
main: com.serendipitymc.refund.refund.refund
author: nickewa
dev-url: http://www.serendiptymc.com
description: A semi-automated refund system for serendipity servers
version: 1.0.7-9baa
commands:
    refund-add:
        description: Used to add items to refund request
        usage: /refund-add <amount> <itemID> (metadata)
    refund-sign:
        description: Used to sign off on refund request when all items have been added
        usage: /refund-sign
    refund:
        description: Main refund command. Separate documentation
        usage: /refund ?
        permission: ssrefund.list
permissions:
    ssrefund.admin:
        default: OP
        description: Allows admins to execute approved refunds
        children:
            ssrefund.execute: true
            ssrefund.approve: true
            ssrefund.create: true
            ssrefund.deny: true
            ssrefund.list: true
            ssrefund.checkuserhistory: true
            ssrefund.testexecute: true
    ssrefund.staff:
        default: OP
        description: Allows staff to create a new refund request and also list existing ones
        children:
            ssrefund.approve: true
            ssrefund.create: true
            ssrefund.list : true
            ssrefund.deny: true
            ssrefund.checkuserhistory: true
    ssrefund.execute:
        default: OP
        description: Allows executing of approved refunds
    ssrefund.approve:
        default: OP
        description: Allows a staff member to approve a finished refund list
    ssrefund.create:
        default: OP
        description: Allows a staff member to create a refund request on behalf of a user
    ssrefund.deny:
        default: OP
        description: Allows a staff member to deny a refund request
    ssrefund.list:
        default: OP
        description: Allows a staff member to list any pending refunds
    ssrefund.checkuserhistory:
        default: OP
        description: Allows a staff member to see a list of previous refunds for a given user
    ssrefund.testexecute:
        default: OP
        description: Allows a staff member to execute a approved refund but send items to himself or herself 